spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/blog}

jwt:
  secret: ${jwt.secret:secret}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:64800000}

server:
  port: 8080

management:
  endpoint:
    web:
      exposure:
        include: health, info, metrics, env, loggers, threaddump, beans
    health:
      show-details: always

info:
  app:
    name: Blog Management System
    version: 1.0.0
    developer: Esther Mushimiyimana

logging:
  level:
    root: INFO
    com.example.managementblog: DEBUG