spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: Gervais0790194121
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/Management

jwt:
  secret: Mysecretkeyjksdncbndmyuwefcgsvahbnnsdyjrtdwu65463287hudnfvdmcvsghty673yedwhsnx
  expiration: 3600000
  refresh-expiration: 604800000

server:
  port: 8080

management:
  endpoint:
    web:
      exposure:
        include: health, info, metrics, env, loggers, threaddump, beans
    health:
      show-details: always

info:
  app:
    name: Blog Management System
    version: 1.0.0
    developer: Esther Mushimiyimana

logging:
  level:
    root: INFO
    com.example.managementblog: DEBUG